'use client';

import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import ClassRolesPage from './class-roles';
import {
  AppData, Attendance, ClassRole, ClassSettings, CloudConfig, HomeworkRecord, HomeworkSubject, Schedule, SeatingPlan, Session, Student, StudentRecord, Task,
  cloudDelete, cloudInsert, cloudReplace, cloudReplaceRows, cloudUpdate, emptyData, loadCloud, loadLocal, resetPassword,
  saveLocal, sessionFromHash, signIn, signUp, tableNames, updatePassword,
} from './data';

type Page='dashboard'|'attendance'|'tasks'|'students'|'seating'|'officers'|'records'|'schedule'|'settings';
type EditState={table:keyof AppData; row:Record<string,unknown>}|null;
const labels:Record<Page,string>={dashboard:'今日總覽',attendance:'出缺勤',tasks:'待辦事項',students:'學生名冊',seating:'座位表',officers:'班幹事',records:'個案紀錄',schedule:'課表設定',settings:'設定與資料'};
const icons:Record<Page,string>={dashboard:'今',attendance:'勤',tasks:'辦',students:'生',seating:'位',officers:'幹',records:'記',schedule:'課',settings:'設'};
const statusLabels:Record<Attendance['status'],string>={present:'出席',late:'遲到',personal:'事假',sick:'病假',absent:'缺席'};
const weekdays=['一','二','三','四','五','六','日'];
const defaultCloudConfig:CloudConfig={
  url:'https://hkqugzmqwlfbxqjaomlh.supabase.co',
  key:'sb_publishable_TRyhbnUEJhWlyiCjOoqtrQ_ZZ7o7UDg',
};
const today=()=>new Date().toISOString().slice(0,10);
const formatDate=(value:string)=>value?new Intl.DateTimeFormat('zh-TW',{month:'numeric',day:'numeric'}).format(new Date(value)):'—';
const formatDateTime=(value:string)=>value?new Intl.DateTimeFormat('zh-TW',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';
const download=(name:string,text:string,type='application/json;charset=utf-8')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);};

export default function Home(){
  const [ready,setReady]=useState(false),[demo,setDemo]=useState(false),[busy,setBusy]=useState(false);
  const [config,setConfig]=useState<CloudConfig|null>(null),[session,setSession]=useState<Session|null>(null);
  const [data,setData]=useState<AppData>(emptyData),[page,setPage]=useState<Page>('dashboard'),[edit,setEdit]=useState<EditState>(null);
  const [toast,setToast]=useState(''),[query,setQuery]=useState(''),[attendanceDate,setAttendanceDate]=useState(today()),[homeworkDate,setHomeworkDate]=useState(today()),[sidebarOpen,setSidebarOpen]=useState(true);
  const importRef=useRef<HTMLInputElement>(null);

  useEffect(()=>{
    const envUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||'',envKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
    const saved=localStorage.getItem('teacher-desk-cloud'); const cfg=envUrl&&envKey?{url:envUrl,key:envKey}:saved?JSON.parse(saved):defaultCloudConfig;
    const recovered=sessionFromHash(); const stored=localStorage.getItem('teacher-desk-session'); const sess=recovered||(stored?JSON.parse(stored):null);
    setConfig(cfg); setSession(sess); setSidebarOpen(localStorage.getItem('teacher-desk-sidebar')!=='closed'); if(recovered) localStorage.setItem('teacher-desk-session',JSON.stringify(recovered)); setReady(true);
  },[]);
  useEffect(()=>{ if(!toast)return; const t=setTimeout(()=>setToast(''),3200); return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{ if(!ready)return; if(demo){setData(loadLocal());return;} if(config&&session){setBusy(true);loadCloud(config,session).then(setData).catch(e=>{setToast(e.message);if(String(e.message).includes('JWT')) logout();}).finally(()=>setBusy(false));}},[ready,demo,config,session]);

  const settings=data.class_settings[0]||({id:'',user_id:session?.user.id||'demo-user',class_name:'我的班級',school_year:'',semester:'',teacher_name:'老師'} as ClassSettings);
  const students=data.students.filter(s=>!s.archived).sort((a,b)=>a.student_no-b.student_no);
  const studentName=(id:string|null)=>data.students.find(s=>s.id===id)?.name||'';
  function commit(next:AppData){setData(next);if(demo)saveLocal(next);}
  async function mutate(table:keyof AppData,row:Record<string,unknown>,patch?:Record<string,unknown>){
    setBusy(true);try{
      const user_id=session?.user.id||'demo-user';
      if(row.id){const saved=demo?{...row,...patch}:await cloudUpdate(config!,session!,table,row.id as string,patch||row);setData(prev=>{const next={...prev,[table]:prev[table].map((x:any)=>x.id===row.id?saved:x)} as AppData;if(demo)saveLocal(next);return next;});}
      else {const input={...row,id:crypto.randomUUID(),user_id};const saved=demo?input:await cloudInsert(config!,session!,table,input);setData(prev=>{const next={...prev,[table]:[...prev[table],saved]} as AppData;if(demo)saveLocal(next);return next;});}
      setEdit(null);setToast('已同步保存');
    }catch(e){setToast((e as Error).message);}finally{setBusy(false);}
  }
  async function remove(table:keyof AppData,id:string){if(!confirm('確定要刪除這筆資料嗎？此操作無法復原。'))return;setBusy(true);try{if(!demo)await cloudDelete(config!,session!,table,id);setData(prev=>{const next={...prev,[table]:prev[table].filter((x:any)=>x.id!==id)} as AppData;if(demo)saveLocal(next);return next;});setToast('已刪除');}catch(e){setToast((e as Error).message);}finally{setBusy(false);}}
  async function updateAttendance(student:Student,status:Attendance['status'],notes=''){
    const old=data.attendance.find(a=>a.student_id===student.id&&a.date===attendanceDate);
    if(old)await mutate('attendance',old,{status,notes}); else await mutate('attendance',{student_id:student.id,date:attendanceDate,status,notes});
  }
  async function saveSchedule(rows:Schedule[]){
    setBusy(true);try{const user_id=session?.user.id||'demo-user';const prepared=rows.map(r=>({...r,id:r.id||crypto.randomUUID(),user_id}));const saved=demo?prepared:await cloudReplaceRows(config!,session!,'schedule',prepared);commit({...data,schedule:saved});setToast('課表已同步保存');}catch(e){setToast((e as Error).message);}finally{setBusy(false);}
  }
  async function addHomeworkRecord(subjectId:string,studentId:string,date:string){
    if(data.homework_records.some(r=>r.date===date&&r.subject_id===subjectId&&r.student_id===studentId)){setToast('這位學生已在該科目的欠功課名單');return;}
    await mutate('homework_records',{subject_id:subjectId,student_id:studentId,date});
  }
  async function removeHomeworkSubject(subject:HomeworkSubject){
    if(!confirm(`確定刪除「${subject.name}」嗎？該科目的欠功課紀錄也會一併刪除。`))return;
    setBusy(true);try{if(!demo){const related=data.homework_records.filter(r=>r.subject_id===subject.id);await Promise.all(related.map(r=>cloudDelete(config!,session!,'homework_records',r.id)));await cloudDelete(config!,session!,'homework_subjects',subject.id);}setData(prev=>{const next={...prev,homework_subjects:prev.homework_subjects.filter(s=>s.id!==subject.id),homework_records:prev.homework_records.filter(r=>r.subject_id!==subject.id)};if(demo)saveLocal(next);return next;});setToast('科目已刪除');}catch(e){setToast((e as Error).message);}finally{setBusy(false);}
  }
  async function addClassRoleMember(roleId:string,studentId:string){
    if(data.class_role_members.some(member=>member.role_id===roleId&&member.student_id===studentId)){setToast('這位學生已在該崗位');return;}
    await mutate('class_role_members',{role_id:roleId,student_id:studentId});
  }
  async function removeClassRole(role:ClassRole){
    if(!confirm(`確定刪除「${role.name}」崗位嗎？`))return;
    setBusy(true);try{if(!demo){const related=data.class_role_members.filter(member=>member.role_id===role.id);await Promise.all(related.map(member=>cloudDelete(config!,session!,'class_role_members',member.id)));await cloudDelete(config!,session!,'class_roles',role.id);}setData(prev=>{const next={...prev,class_roles:prev.class_roles.filter(item=>item.id!==role.id),class_role_members:prev.class_role_members.filter(member=>member.role_id!==role.id)};if(demo)saveLocal(next);return next;});setToast('崗位已刪除');}catch(e){setToast((e as Error).message);}finally{setBusy(false);}
  }
  async function reorderHomeworkSubjects(ids:string[]){
    const order=new Map(ids.map((id,index)=>[id,index+1]));
    const changed=data.homework_subjects.filter(subject=>order.has(subject.id)&&subject.sort_order!==order.get(subject.id));
    if(!changed.length)return;
    setBusy(true);try{
      if(!demo)await Promise.all(changed.map(subject=>cloudUpdate(config!,session!,'homework_subjects',subject.id,{sort_order:order.get(subject.id)})));
      setData(prev=>{const next={...prev,homework_subjects:prev.homework_subjects.map(subject=>order.has(subject.id)?{...subject,sort_order:order.get(subject.id)!}:subject)};if(demo)saveLocal(next);return next;});
      setToast('科目順序已保存');
    }catch(e){setToast((e as Error).message);}finally{setBusy(false);}
  }
  function toggleSidebar(){setSidebarOpen(open=>{localStorage.setItem('teacher-desk-sidebar',open?'closed':'open');return !open;});}
  function logout(){localStorage.removeItem('teacher-desk-session');setSession(null);setData(emptyData);setDemo(false);}
  function startDemo(){setDemo(true);setSession(null);setData(loadLocal());}

  if(!ready)return <div className="loadingPage">正在準備工作台…</div>;
  if(!demo&&(!config||!session))return <AuthScreen config={config} onConfig={cfg=>{localStorage.setItem('teacher-desk-cloud',JSON.stringify(cfg));setConfig(cfg);}} onSession={s=>{localStorage.setItem('teacher-desk-session',JSON.stringify(s));setSession(s);}} onDemo={startDemo}/>;

  const pageProps={data,students,studentName,query,setQuery,setEdit,remove,busy};
  return <main className={`shell ${sidebarOpen?'':'sidebarClosed'}`}>
    <aside className="sidebar">
      <div className="brand"><span className="brandMark">班</span><span>班主任工作台</span></div>
      <nav className="nav" aria-label="主要導覽">{(Object.keys(labels) as Page[]).map(p=><button key={p} className={`navItem ${page===p?'active':''}`} onClick={()=>setPage(p)}><span>{icons[p]}</span>{labels[p]}</button>)}</nav>
      <div className="sidebarFoot"><div className="avatar">{settings.teacher_name.slice(0,1)}</div><div><strong>{settings.teacher_name}</strong><small>{settings.class_name}</small></div><button title="登出" onClick={logout}>↗</button></div>
    </aside>
    <section className="workspace">
      <header className="topbar"><div className="topbarLead"><button className="sidebarToggle" aria-label={sidebarOpen?'關閉側欄':'顯示側欄'} title={sidebarOpen?'關閉側欄':'顯示側欄'} onClick={toggleSidebar}>☰</button><div><p>{new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date())}</p><h1>{page==='dashboard'?'今日欠功課':labels[page]}</h1></div></div><div className="topActions"><span className={`syncDot ${demo?'demo':''}`}>{busy?'同步中…':demo?'示範模式':'已同步'}</span><button className="ghostButton" onClick={()=>setPage('settings')}>設定</button><button className="primaryButton" onClick={()=>setEdit({table:'tasks',row:{}})}>＋ 快速新增</button></div></header>
      {demo&&<div className="demoBanner"><strong>示範模式</strong>　資料只保存在這台裝置。設定 Supabase 後即可跨裝置同步。<button onClick={()=>{setDemo(false);setData(emptyData);}}>設定雲端</button></div>}
      <div className="content">
        {page==='dashboard'&&<HomeworkTracker students={students} subjects={data.homework_subjects} records={data.homework_records.filter(r=>r.date===homeworkDate)} date={homeworkDate} setDate={setHomeworkDate} addRecord={addHomeworkRecord} removeRecord={id=>remove('homework_records',id)} addSubject={name=>mutate('homework_subjects',{name,sort_order:(Math.max(0,...data.homework_subjects.map(s=>s.sort_order))+1)})} removeSubject={removeHomeworkSubject} reorderSubjects={reorderHomeworkSubjects} exportCsv={()=>exportHomework(data,homeworkDate)}/>}
        {page==='attendance'&&<AttendancePage students={students} records={data.attendance} date={attendanceDate} setDate={setAttendanceDate} update={updateAttendance} markAll={()=>Promise.all(students.map(s=>updateAttendance(s,'present','')))} exportCsv={()=>exportAttendance(data,attendanceDate)} exportMonth={()=>exportMonthAttendance(data,attendanceDate)}/>}
        {page==='tasks'&&<TasksPage {...pageProps} tasks={data.tasks} toggle={t=>mutate('tasks',t,{completed:!t.completed})}/>} 
        {page==='students'&&<StudentsPage {...pageProps}/>} 
        {page==='seating'&&<SeatingPage students={students} plans={data.seating_plans} settings={settings} save={layout=>mutate('seating_plans',{plan_date:today(),created_at:new Date().toISOString(),layout})}/>} 
        {page==='officers'&&<ClassRolesPage students={students} roles={data.class_roles} members={data.class_role_members} addRole={name=>mutate('class_roles',{name,sort_order:(Math.max(0,...data.class_roles.map(role=>role.sort_order))+1)})} removeRole={removeClassRole} addMember={addClassRoleMember} removeMember={id=>remove('class_role_members',id)}/>}
        {page==='records'&&<RecordsPage {...pageProps} records={data.student_records}/>} 
        {page==='schedule'&&<SchedulePage schedule={data.schedule} save={saveSchedule}/>} 
        {page==='settings'&&<SettingsPage settings={settings} demo={demo} email={session?.user.email||''} save={row=>mutate('class_settings',row)} exportJson={()=>download(`班主任工作台-${today()}.json`,JSON.stringify(data,null,2))} exportCsv={()=>exportCsv(data)} importClick={()=>importRef.current?.click()} changePassword={async password=>{if(!config||!session)return;await updatePassword(config,session.access_token,password);setToast('密碼已更新');}} logout={logout}/>} 
      </div>
    </section>
    <nav className="mobileNav" aria-label="平板導覽">{(Object.keys(labels) as Page[]).map(p=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}><span>{icons[p]}</span>{labels[p].replace('今日總覽','今日').replace('待辦事項','待辦').replace('學生名冊','學生').replace('個案紀錄','紀錄').replace('課表設定','課表').replace('設定與資料','設定')}</button>)}</nav>
    {edit&&<Editor edit={edit} students={students} onClose={()=>setEdit(null)} onSave={(row)=>mutate(edit.table,row)}/>} 
    <input ref={importRef} hidden type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const raw=JSON.parse(await f.text());const imported={...emptyData,...raw,seating_plans:Array.isArray(raw.seating_plans)?raw.seating_plans:[]} as AppData;if(!tableNames.every(t=>Array.isArray(imported[t])))throw new Error('備份格式不正確');if(!confirm('還原會取代目前所有資料，確定繼續嗎？'))return;setBusy(true);if(demo)saveLocal(imported);else await cloudReplace(config!,session!,imported);setData(demo?imported:await loadCloud(config!,session!));setToast('備份已還原');}catch(err){setToast((err as Error).message);}finally{setBusy(false);e.target.value='';}}}/>
    {toast&&<div className="toast" role="status">{toast}</div>}
  </main>;
}

function AuthScreen({config,onConfig,onSession,onDemo}:{config:CloudConfig|null;onConfig:(c:CloudConfig)=>void;onSession:(s:Session)=>void;onDemo:()=>void}){
  const [mode,setMode]=useState<'login'|'signup'|'reset'|'config'>(config?'login':'config'),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setMsg('');try{
    if(mode==='config'){const url=String(form.get('url')).replace(/\/$/,'');const key=String(form.get('key'));if(!url.startsWith('https://')||!key)throw new Error('請輸入有效的 Supabase HTTPS 網址與 Publishable Key');onConfig({url,key});setMode('login');setMsg('雲端連線設定已保存');return;}
    if(!config)throw new Error('請先設定雲端連線');const email=String(form.get('email')),password=String(form.get('password'));
    if(mode==='login')onSession(await signIn(config,email,password));
    if(mode==='signup'){await signUp(config,email,password);setMsg('帳號已建立。若專案要求 Email 驗證，請先到信箱確認。');setMode('login');}
    if(mode==='reset'){await resetPassword(config,email,`${location.origin}${process.env.NEXT_PUBLIC_BASE_PATH||''}`);setMsg('密碼重設信已寄出，請查看信箱。');}
  }catch(err){setMsg((err as Error).message);}finally{setBusy(false);}}
  return <main className="authPage"><section className="authIntro"><div className="brand authBrand"><span className="brandMark">班</span><span>班主任工作台</span></div><div><span className="eyebrow">每天，從掌握全班開始</span><h1>課表、出勤、待辦<br/>與學生追蹤，一處完成。</h1><p>為班主任整理每天真正需要處理的資訊，讓平板與電腦保持一致。</p></div><div className="authFeature"><b>今日重點</b><span>快速點名、即將到期的任務、需要回訪的學生。</span></div></section>
    <section className="authFormWrap"><form className="authCard" onSubmit={submit}>
      <span className="eyebrow">SECURE WORKSPACE</span><h2>{mode==='login'?'登入工作台':mode==='signup'?'建立老師帳號':mode==='reset'?'重設密碼':'連接 Supabase'}</h2><p>{mode==='config'?'輸入 Supabase 專案的公開連線資訊；管理員密鑰絕不可填在這裡。':'學生資料只會顯示給已登入的帳號。'}</p>
      {mode==='config'?<><label>Project URL<input name="url" type="url" placeholder="https://xxxxx.supabase.co" required/></label><label>Publishable／Anon Key<textarea name="key" rows={3} required/></label></>:<><label>Email<input name="email" type="email" autoComplete="email" required/></label>{mode!=='reset'&&<label>密碼<input name="password" type="password" minLength={8} autoComplete={mode==='login'?'current-password':'new-password'} required/></label>}</>}
      {msg&&<div className="formMessage">{msg}</div>}<button className="authSubmit" disabled={busy}>{busy?'請稍候…':mode==='login'?'登入':mode==='signup'?'建立帳號':mode==='reset'?'寄送重設信':'保存連線設定'}</button>
      <div className="authLinks">{mode==='login'&&<><button type="button" onClick={()=>setMode('signup')}>建立帳號</button><button type="button" onClick={()=>setMode('reset')}>忘記密碼</button></>}{mode!=='login'&&mode!=='config'&&<button type="button" onClick={()=>setMode('login')}>返回登入</button>}{config&&<button type="button" onClick={()=>setMode('config')}>變更雲端設定</button>}</div>
      <div className="divider"><span>或</span></div><button className="demoButton" type="button" onClick={onDemo}>先試用示範資料</button>
    </form></section>
  </main>;
}

function HomeworkTracker({students,subjects,records,date,setDate,addRecord,removeRecord,addSubject,removeSubject,reorderSubjects,exportCsv}:{students:Student[];subjects:HomeworkSubject[];records:HomeworkRecord[];date:string;setDate:(date:string)=>void;addRecord:(subjectId:string,studentId:string,date:string)=>Promise<void>;removeRecord:(id:string)=>void;addSubject:(name:string)=>Promise<void>;removeSubject:(subject:HomeworkSubject)=>Promise<void>;reorderSubjects:(ids:string[])=>Promise<void>;exportCsv:()=>void}){
  const [selectedStudents,setSelectedStudents]=useState<Record<string,string>>({}),[newSubject,setNewSubject]=useState(''),[draggedSubject,setDraggedSubject]=useState('');
  const sorted=[...subjects].sort((a,b)=>a.sort_order-b.sort_order||a.name.localeCompare(b.name));
  const student=(id:string)=>students.find(s=>s.id===id);
  async function assign(subjectId:string){const studentId=selectedStudents[subjectId];if(!studentId)return;await addRecord(subjectId,studentId,date);setSelectedStudents(prev=>({...prev,[subjectId]:''}));}
  async function submitSubject(e:FormEvent){e.preventDefault();const name=newSubject.trim();if(!name||subjects.some(s=>s.name===name))return;await addSubject(name);setNewSubject('');}
  function moveSubject(sourceId:string,targetId:string){if(!sourceId||sourceId===targetId)return;const ids=sorted.map(subject=>subject.id),from=ids.indexOf(sourceId),to=ids.indexOf(targetId);if(from<0||to<0)return;ids.splice(to,0,ids.splice(from,1)[0]);setDraggedSubject('');reorderSubjects(ids);}
  return <section className="homeworkPanel"><div className="homeworkHead"><div><span className="eyebrow">HOMEWORK</span><h2>{date===today()?'今日欠功課':`${formatDate(date)} 欠功課`}</h2><p>選擇日期及學生，即可登記或查看當日欠功課紀錄。</p></div><div className="homeworkTools"><label>日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button type="button" onClick={exportCsv}>匯出 CSV</button></div></div>
    <form className="subjectAdder" onSubmit={submitSubject}><input aria-label="新增科目名稱" value={newSubject} onChange={e=>setNewSubject(e.target.value)} placeholder="新增科目"/><button disabled={!newSubject.trim()}>＋ 加入科目</button></form>
    <div className="homeworkSubjects">{sorted.map(subject=>{const owing=records.filter(r=>r.subject_id===subject.id);const available=students.filter(s=>!owing.some(r=>r.student_id===s.id));return <article key={subject.id} className={`homeworkSubject ${draggedSubject===subject.id?'dragging':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();moveSubject(e.dataTransfer.getData('text/plain'),subject.id)}}><div className="subjectName" draggable onDragStart={e=>{setDraggedSubject(subject.id);e.dataTransfer.setData('text/plain',subject.id);e.dataTransfer.effectAllowed='move'}} onDragEnd={()=>setDraggedSubject('')} title="拖曳更改科目順序"><i aria-hidden="true">⋮⋮</i><strong>{subject.name}</strong><span>{owing.length} 人</span><button aria-label={`刪除${subject.name}`} onClick={()=>removeSubject(subject)}>×</button></div><div className="subjectAssign"><select aria-label={`選擇${subject.name}欠功課學生`} value={selectedStudents[subject.id]||''} onChange={e=>setSelectedStudents(prev=>({...prev,[subject.id]:e.target.value}))}><option value="">選擇學生…</option>{available.map(s=><option key={s.id} value={s.id}>{String(s.student_no).padStart(2,'0')}　{s.name}</option>)}</select><button type="button" disabled={!selectedStudents[subject.id]} onClick={()=>assign(subject.id)}>加入</button></div><div className={`owingStudents ${!owing.length?'emptyOwing':''}`}>{owing.length?owing.map(record=>{const s=student(record.student_id);return <span key={record.id}><b>{s?String(s.student_no).padStart(2,'0'):'—'}</b>{s?.name||'已刪除學生'}<button aria-label={`移除${s?.name||'學生'}的${subject.name}紀錄`} onClick={()=>removeRecord(record.id)}>×</button></span>}):<em>尚未登記學生</em>}</div></article>})}{!sorted.length&&<Empty text="尚未設定科目，請先新增科目。"/>}</div>
  </section>;
}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function dataNo(students:Student[],id:string){return String(students.find(s=>s.id===id)?.student_no||'—').padStart(2,'0')}

function AttendancePage({students,records,date,setDate,update,markAll,exportCsv,exportMonth}:{students:Student[];records:Attendance[];date:string;setDate:(d:string)=>void;update:(s:Student,v:Attendance['status'],notes?:string)=>void;markAll:()=>void;exportCsv:()=>void;exportMonth:()=>void}){
  const [detail,setDetail]=useState<{student:Student;status:'late'|'personal'|'sick';time:string;reason:string}|null>(null);
  const byStudent=(id:string)=>records.find(a=>a.student_id===id&&a.date===date);
  const counts=Object.fromEntries(Object.keys(statusLabels).map(k=>[k,students.filter(s=>byStudent(s.id)?.status===k).length]));
  const unmarked=students.filter(s=>!byStudent(s.id)).length;
  function choose(student:Student,status:Attendance['status']){if(status==='late'||status==='personal'||status==='sick'){const old=byStudent(student.id)?.notes||'';setDetail({student,status,time:old.match(/\d{2}:\d{2}/)?.[0]||new Date().toTimeString().slice(0,5),reason:old.replace(/^.+?：/,'')});}else update(student,status,'');}
  function saveDetail(){if(!detail)return;const notes=detail.status==='late'?`遲到時間：${detail.time}`:`${statusLabels[detail.status]}原因：${detail.reason.trim()}`;update(detail.student,detail.status,notes);setDetail(null);}
  return <section className="pageSection"><div className="sectionTitle"><div><span className="eyebrow">ATTENDANCE</span><h2>每日點名</h2><p>未操作的學生會保持「未點名」，不會自動當作出席。</p></div><div className="sectionActions attendanceActions"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button onClick={exportCsv}>匯出當天</button><button onClick={exportMonth}>按月匯出</button><button className="primaryButton" onClick={markAll}>全班出席</button></div></div>
    <div className="miniStats"><span className="unmarked"><b>{unmarked}</b>未點名</span>{Object.entries(statusLabels).map(([k,l])=><span key={k} className={k}><b>{counts[k]}</b>{l}</span>)}</div>
    <div className="attendanceList"><div className="tableHead"><span>學號</span><span>學生</span><span>出勤狀態</span></div>{students.map(s=>{const current=byStudent(s.id);return <div className="attendanceRow" key={s.id}><b>{String(s.student_no).padStart(2,'0')}</b><div className="attendanceStudent"><strong>{s.name}</strong>{current?.notes?<small>{current.notes}</small>:!current?<small className="unmarkedText">未點名</small>:null}</div><div className="statusPicker">{Object.entries(statusLabels).map(([v,l])=><button key={v} className={current?.status===v?v:''} onClick={()=>choose(s,v as Attendance['status'])}>{l}</button>)}</div></div>})}</div>
    {detail&&<div className="modalBack" role="presentation"><form className="modal detailModal" onSubmit={e=>{e.preventDefault();saveDetail()}}><div className="modalHead"><div><span className="eyebrow">ATTENDANCE</span><h2>{detail.student.name} · {statusLabels[detail.status]}</h2></div><button type="button" onClick={()=>setDetail(null)}>×</button></div>{detail.status==='late'?<label>遲到時間<input type="time" value={detail.time} onChange={e=>setDetail({...detail,time:e.target.value})} required/></label>:<label>{statusLabels[detail.status]}原因<textarea rows={4} value={detail.reason} onChange={e=>setDetail({...detail,reason:e.target.value})} required/></label>}<div className="modalActions"><button type="button" onClick={()=>setDetail(null)}>取消</button><button className="primaryButton">保存</button></div></form></div>}
  </section>;
}

type CommonProps={data:AppData;students:Student[];studentName:(id:string|null)=>string;query:string;setQuery:(s:string)=>void;setEdit:(e:EditState)=>void;remove:(t:keyof AppData,id:string)=>void;busy:boolean};
function PageHeader({eyebrow,title,description,search,onAdd,addLabel='新增'}:{eyebrow:string;title:string;description:string;search?:{value:string;set:(v:string)=>void};onAdd:()=>void;addLabel?:string}){return <div className="sectionTitle"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div><div className="sectionActions">{search&&<input type="search" placeholder="搜尋…" value={search.value} onChange={e=>search.set(e.target.value)}/>}<button className="primaryButton" onClick={onAdd}>＋ {addLabel}</button></div></div>}
function TasksPage({data,students,studentName,query,setQuery,setEdit,remove,toggle}:CommonProps&{tasks:Task[];toggle:(t:Task)=>void}){const rows=data.tasks.filter(t=>t.title.includes(query)||studentName(t.student_id).includes(query)).sort((a,b)=>Number(a.completed)-Number(b.completed)||a.due_at.localeCompare(b.due_at));return <section className="pageSection"><PageHeader eyebrow="TASKS" title="待辦事項" description="把班級、行政與學生相關工作放在同一份清單。" search={{value:query,set:setQuery}} onAdd={()=>setEdit({table:'tasks',row:{}})} addLabel="新增待辦"/><div className="dataCards">{rows.map(t=><article className={`dataCard taskData ${t.completed?'completed':''}`} key={t.id}><button className="roundCheck" onClick={()=>toggle(t)}>{t.completed?'✓':''}</button><div><div className="tagLine"><span className={`priority ${t.priority}`}>{t.priority==='high'?'高優先':t.priority==='low'?'低優先':'一般'}</span><span>{t.category}</span>{t.student_id&&<span>{studentName(t.student_id)}</span>}</div><h3>{t.title}</h3><p>{formatDateTime(t.due_at)}</p></div><div className="rowActions"><button onClick={()=>setEdit({table:'tasks',row:t as any})}>編輯</button><button className="danger" onClick={()=>remove('tasks',t.id)}>刪除</button></div></article>)}{!rows.length&&<Empty text="沒有符合條件的待辦"/>}</div></section>}
function StudentsPage({students,query,setQuery,setEdit}:CommonProps){const rows=students.filter(s=>s.name.includes(query)||String(s.student_no).includes(query)||s.tags.some(t=>t.includes(query)));return <section className="pageSection"><PageHeader eyebrow="STUDENTS" title="學生名冊" description={`目前共有 ${students.length} 位在班學生。`} search={{value:query,set:setQuery}} onAdd={()=>setEdit({table:'students',row:{}})} addLabel="新增學生"/><div className="studentGrid">{rows.map((s,i)=><article className="studentCard" key={s.id}><div className={`studentAvatar ${i%3===0?'lavender':i%3===1?'mint':'peach'}`}>{String(s.student_no).padStart(2,'0')}</div><div className="studentCardMain"><h3>{s.name}</h3><p>{s.guardian_name||'未填監護人'} · {s.guardian_phone||'未填電話'}</p><div className="tags">{s.tags.map(t=><span key={t}>{t}</span>)}</div></div><button onClick={()=>setEdit({table:'students',row:s as any})}>管理</button></article>)}{!rows.length&&<Empty text="找不到學生"/>}</div></section>}
function RecordsPage({records,students,studentName,query,setQuery,setEdit,remove}:CommonProps&{records:StudentRecord[]}){const [selected,setSelected]=useState('');const rows=records.filter(r=>(!selected||r.student_id===selected)&&(r.content.includes(query)||r.record_type.includes(query)||studentName(r.student_id).includes(query))).sort((a,b)=>b.record_date.localeCompare(a.record_date));return <section className="pageSection"><div className="sectionTitle"><div><span className="eyebrow">RECORDS</span><h2>個案紀錄</h2><p>先選擇學生，再新增或查看他的紀錄。</p></div><div className="sectionActions recordsTools"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">全部學生</option>{students.map(s=><option key={s.id} value={s.id}>{s.student_no}　{s.name}</option>)}</select><input type="search" placeholder="搜尋內容…" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>exportRecords(rows,students)}>匯出</button><button className="primaryButton" onClick={()=>setEdit({table:'student_records',row:{student_id:selected}})}>＋ 新增紀錄</button></div></div><div className="recordTimeline">{rows.map(r=><article className="recordCard" key={r.id}><div className="recordDate"><b>{formatDate(r.record_date)}</b><span>{r.record_type}</span></div><div><h3>{studentName(r.student_id)} <small>學號 {dataNo(students,r.student_id)}</small></h3><p>{r.content}</p>{r.follow_up_date&&<em>追蹤：{formatDate(r.follow_up_date)}</em>}</div><div className="rowActions"><button onClick={()=>setEdit({table:'student_records',row:r as any})}>編輯</button><button className="danger" onClick={()=>remove('student_records',r.id)}>刪除</button></div></article>)}{!rows.length&&<Empty text="尚無個案紀錄"/>}</div></section>}

function SeatingPage({students,plans,settings,save}:{students:Student[];plans:SeatingPlan[];settings:ClassSettings;save:(layout:(string|null)[])=>void}){const latest=[...plans].sort((a,b)=>(b.created_at||b.plan_date).localeCompare(a.created_at||a.plan_date))[0];const initial=()=>latest?.layout?.length===36?latest.layout:[...students.map(s=>s.id),...Array(Math.max(0,36-students.length)).fill(null)].slice(0,36);const [layout,setLayout]=useState<(string|null)[]>(initial),[picked,setPicked]=useState<number|null>(null);useEffect(()=>setLayout(initial()),[latest?.id,students.map(s=>s.id).join(',')]);const student=(id:string|null)=>students.find(s=>s.id===id);function swap(a:number,b:number){if(!Number.isInteger(a)||a<0||a>=36||b<0||b>=36)return;setLayout(old=>{const next=[...old];[next[a],next[b]]=[next[b],next[a]];return next});setPicked(null)}function clickSeat(i:number){if(picked===null)setPicked(i);else if(picked===i)setPicked(null);else swap(picked,i)}return <section className="pageSection"><div className="sectionTitle"><div><span className="eyebrow">SEATING</span><h2>6 × 6 座位表</h2><p>黑板在下方、右邊是窗；拖曳學生調位，平板也可點選兩個座位交換。</p></div><div className="sectionActions"><span className="savedStamp">{latest?`最近保存：${formatDateTime(latest.created_at||latest.plan_date)}`:'尚未保存'}</span><button onClick={()=>exportSeating(layout,students,settings)}>匯出</button><button className="primaryButton" onClick={()=>save(layout)}>保存座位表</button></div></div><div className="classroomMap"><div className="roomMarker rearDoor">後門</div><div className="seatingGridWrap"><div className="seatingGrid">{layout.map((id,i)=>{const s=student(id);return <button key={i} draggable={Boolean(s)} onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();swap(Number(e.dataTransfer.getData('text/plain')),i)}} onClick={()=>clickSeat(i)} className={`seat ${picked===i?'picked':''} ${s?'occupied':'emptySeat'}`}><small>{i+1}</small>{s?<><b>{s.student_no}</b><span>{s.name}</span></>:<em>空位</em>}</button>})}</div></div><div className="roomMarker windows">窗</div><div className="roomMarker frontDoor">前門</div><div className="blackboard">黑板</div></div></section>}

function SchedulePage({schedule,save}:{schedule:Schedule[];save:(rows:Schedule[])=>Promise<void>}){const [cells,setCells]=useState<Record<string,string>>({});useEffect(()=>setCells(Object.fromEntries(schedule.map(s=>[`${s.weekday}-${s.period}`,s.subject]))),[schedule]);const times=['08:10','09:00','09:50','10:50','11:40','13:30','14:20','15:10','16:00','16:50'];async function saveGrid(){const rows:Schedule[]=[];for(let weekday=1;weekday<=5;weekday++)for(let period=1;period<=10;period++){const subject=(cells[`${weekday}-${period}`]||'').trim();if(subject){const old=schedule.find(s=>s.weekday===weekday&&s.period===period);rows.push({id:old?.id||'',user_id:old?.user_id||'',weekday,period,start_time:old?.start_time||times[period-1],subject,location:old?.location||'本班教室'});}}await save(rows)}return <section className="pageSection"><div className="sectionTitle"><div><span className="eyebrow">SCHEDULE</span><h2>每週課表</h2><p>上方是星期，左側是第一至第十節，直接在格子輸入科目。</p></div><div className="sectionActions"><button className="primaryButton" onClick={saveGrid}>保存課表</button></div></div><div className="scheduleTableWrap"><table className="scheduleTable"><thead><tr><th>節次</th>{weekdays.slice(0,5).map(d=><th key={d}>星期{d}</th>)}</tr></thead><tbody>{times.map((_,pi)=><tr key={pi}><th>第{pi+1}節</th>{weekdays.slice(0,5).map((d,di)=>{const key=`${di+1}-${pi+1}`;return <td key={key}><input aria-label={`星期${d}第${pi+1}節`} value={cells[key]||''} onChange={e=>setCells({...cells,[key]:e.target.value})} placeholder="科目"/></td>})}</tr>)}</tbody></table></div></section>}
function SettingsPage({settings,demo,email,save,exportJson,exportCsv,importClick,changePassword,logout}:{settings:ClassSettings;demo:boolean;email:string;save:(s:Record<string,unknown>)=>void;exportJson:()=>void;exportCsv:()=>void;importClick:()=>void;changePassword:(p:string)=>Promise<void>;logout:()=>void}){const [row,setRow]=useState(settings),[password,setPassword]=useState('');useEffect(()=>setRow(settings),[settings]);return <section className="pageSection"><div className="sectionTitle"><div><span className="eyebrow">SETTINGS</span><h2>設定與資料</h2><p>管理班級資訊、帳號安全與資料備份。</p></div></div><div className="settingsGrid"><form className="settingsCard" onSubmit={e=>{e.preventDefault();save(row as any)}}><h3>班級基本資料</h3><div className="formGrid"><label>班級名稱<input value={row.class_name} onChange={e=>setRow({...row,class_name:e.target.value})}/></label><label>老師名稱<input value={row.teacher_name} onChange={e=>setRow({...row,teacher_name:e.target.value})}/></label><label>學年<input value={row.school_year} onChange={e=>setRow({...row,school_year:e.target.value})}/></label><label>學期<input value={row.semester} onChange={e=>setRow({...row,semester:e.target.value})}/></label></div><button className="primaryButton">保存設定</button></form><section className="settingsCard"><h3>備份與匯出</h3><p>JSON 可完整還原工作台；CSV 適合用試算表查看。</p><div className="buttonStack"><button onClick={exportJson}>匯出完整 JSON</button><button onClick={exportCsv}>匯出 CSV</button><button onClick={importClick}>從 JSON 還原</button></div></section><section className="settingsCard"><h3>帳號安全</h3><p>{demo?'示範模式沒有登入帳號。':email}</p>{!demo&&<form onSubmit={async e=>{e.preventDefault();await changePassword(password);setPassword('')}}><label>新密碼<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label><button>更新密碼</button></form>}<button className="dangerButton" onClick={logout}>{demo?'離開示範模式':'登出工作台'}</button></section></div></section>}

function Editor({edit,students,onClose,onSave}:{edit:NonNullable<EditState>;students:Student[];onClose:()=>void;onSave:(r:Record<string,unknown>)=>void}){
  const row=edit.row as any; const [tags,setTags]=useState((row.tags||[]).join('、'));
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));const base={...row,...values};if(edit.table==='students'){base.student_no=Number(base.student_no);base.tags=tags.split(/[、,]/).map((x:string)=>x.trim()).filter(Boolean);base.archived=Boolean(row.archived);}if(edit.table==='schedule'){base.weekday=Number(base.weekday);base.period=Number(base.period);}if(edit.table==='tasks')base.student_id=base.student_id||null;if(edit.table==='student_records')base.follow_up_date=base.follow_up_date||null;onSave(base);}
  const title=edit.table==='students'?'學生資料':edit.table==='tasks'?'待辦事項':edit.table==='student_records'?'個案紀錄':'課程';
  return <div className="modalBack" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="modal" onSubmit={submit}><div className="modalHead"><div><span className="eyebrow">EDITOR</span><h2>{row.id?'編輯':'新增'}{title}</h2></div><button type="button" onClick={onClose}>×</button></div>
    {edit.table==='students'&&<div className="formGrid"><label>學號<input name="student_no" type="number" min="1" defaultValue={row.student_no} required/></label><label>姓名<input name="name" defaultValue={row.name} required/></label><label>監護人<input name="guardian_name" defaultValue={row.guardian_name}/></label><label>聯絡電話<input name="guardian_phone" defaultValue={row.guardian_phone}/></label><label className="wide">標籤（以頓號分隔）<input value={tags} onChange={e=>setTags(e.target.value)}/></label><label className="wide">基本備註<textarea name="notes" rows={4} defaultValue={row.notes}/></label>{row.id&&<label className="wide checkLabel"><input type="checkbox" checked={Boolean(row.archived)} onChange={e=>row.archived=e.target.checked}/> 封存此學生</label>}</div>}
    {edit.table==='tasks'&&<div className="formGrid"><label className="wide">待辦內容<textarea name="title" rows={3} defaultValue={row.title} required/></label><label>期限<input name="due_at" type="datetime-local" defaultValue={row.due_at?.slice(0,16)||`${today()}T16:00`} required/></label><label>優先程度<select name="priority" defaultValue={row.priority||'normal'}><option value="low">低</option><option value="normal">一般</option><option value="high">高</option></select></label><label>分類<input name="category" defaultValue={row.category||'班級事務'}/></label><label>關聯學生<select name="student_id" defaultValue={row.student_id||''}><option value="">不指定</option>{students.map(s=><option key={s.id} value={s.id}>{s.student_no}　{s.name}</option>)}</select></label></div>}
    {edit.table==='student_records'&&<div className="formGrid"><label>學生<select name="student_id" defaultValue={row.student_id||''} required><option value="">請選擇</option>{students.map(s=><option key={s.id} value={s.id}>{s.student_no}　{s.name}</option>)}</select></label><label>紀錄日期<input name="record_date" type="date" defaultValue={row.record_date||today()} required/></label><label>紀錄類型<select name="record_type" defaultValue={row.record_type||'日常觀察'}><option>日常觀察</option><option>談話紀錄</option><option>家長聯絡</option><option>學習狀況</option><option>其他事件</option></select></label><label>下次追蹤<input name="follow_up_date" type="date" defaultValue={row.follow_up_date||''}/></label><label className="wide">內容<textarea name="content" rows={6} defaultValue={row.content} required/></label></div>}
    {edit.table==='schedule'&&<div className="formGrid"><label>星期<select name="weekday" defaultValue={row.weekday||1}>{weekdays.slice(0,5).map((d,i)=><option key={d} value={i+1}>星期{d}</option>)}</select></label><label>節次<input name="period" type="number" min="1" defaultValue={row.period||1} required/></label><label>開始時間<input name="start_time" type="time" defaultValue={row.start_time?.slice(0,5)||'08:10'} required/></label><label>科目<input name="subject" defaultValue={row.subject} required/></label><label className="wide">地點<input name="location" defaultValue={row.location||'本班教室'}/></label></div>}
    <div className="modalActions"><button type="button" onClick={onClose}>取消</button><button className="primaryButton">保存並同步</button></div></form></div>;
}

function exportAttendance(data:AppData,date:string){const q=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;let csv='日期,學號,學生,出勤狀態,遲到時間或請假原因\r\n';for(const s of data.students.filter(s=>!s.archived).sort((a,b)=>a.student_no-b.student_no)){const a=data.attendance.find(x=>x.student_id===s.id&&x.date===date);csv+=[date,s.student_no,s.name,a?statusLabels[a.status]:'未點名',a?.notes||''].map(q).join(',')+'\r\n';}download(`出缺勤-${date}.csv`,'\ufeff'+csv,'text/csv;charset=utf-8');}
function exportMonthAttendance(data:AppData,date:string){const q=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`,month=date.slice(0,7);let csv='日期,學號,學生,出勤狀態,遲到時間或請假原因\r\n';const rows=data.attendance.filter(a=>a.date.startsWith(month)).sort((a,b)=>a.date.localeCompare(b.date)||((data.students.find(s=>s.id===a.student_id)?.student_no||0)-(data.students.find(s=>s.id===b.student_id)?.student_no||0)));for(const a of rows){const s=data.students.find(x=>x.id===a.student_id);csv+=[a.date,s?.student_no||'',s?.name||'已刪除學生',statusLabels[a.status],a.notes||''].map(q).join(',')+'\r\n';}download(`出缺勤-${month}.csv`,'\ufeff'+csv,'text/csv;charset=utf-8');}
function exportHomework(data:AppData,date:string){const q=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;let csv='日期,科目,學號,學生\r\n';const rows=data.homework_records.filter(r=>r.date===date).sort((a,b)=>{const subjectA=data.homework_subjects.find(s=>s.id===a.subject_id)?.sort_order||0,subjectB=data.homework_subjects.find(s=>s.id===b.subject_id)?.sort_order||0;const studentA=data.students.find(s=>s.id===a.student_id)?.student_no||0,studentB=data.students.find(s=>s.id===b.student_id)?.student_no||0;return subjectA-subjectB||studentA-studentB;});for(const r of rows){const subject=data.homework_subjects.find(s=>s.id===r.subject_id),student=data.students.find(s=>s.id===r.student_id);csv+=[date,subject?.name||'已刪除科目',student?.student_no||'',student?.name||'已刪除學生'].map(q).join(',')+'\r\n';}download(`欠功課-${date}.csv`,'\ufeff'+csv,'text/csv;charset=utf-8');}
function exportRecords(rows:StudentRecord[],students:Student[]){const q=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;let csv='日期,學號,學生,紀錄類型,內容,下次追蹤\r\n';for(const r of rows){const s=students.find(x=>x.id===r.student_id);csv+=[r.record_date,s?.student_no,s?.name,r.record_type,r.content,r.follow_up_date||''].map(q).join(',')+'\r\n';}download(`個案紀錄-${today()}.csv`,'\ufeff'+csv,'text/csv;charset=utf-8');}
function exportSeating(layout:(string|null)[],students:Student[],settings:ClassSettings){const q=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;let csv=[`${settings.class_name}座位表`,`保存日期：${today()}`].map(q).join(',')+'\r\n';for(let row=0;row<6;row++){csv+=layout.slice(row*6,row*6+6).map(id=>{const s=students.find(x=>x.id===id);return q(s?`${s.name}(${s.student_no})`:'空位')}).join(',')+'\r\n';}download(`${settings.class_name}-座位表-${today()}.csv`,'\ufeff'+csv,'text/csv;charset=utf-8');}
function exportCsv(data:AppData){const q=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;let csv='類型,日期,學號,學生,狀態或分類,內容\r\n';for(const a of data.attendance){const s=data.students.find(x=>x.id===a.student_id);csv+=['出勤',a.date,s?.student_no,s?.name,statusLabels[a.status],a.notes].map(q).join(',')+'\r\n';}for(const r of data.student_records){const s=data.students.find(x=>x.id===r.student_id);csv+=['個案紀錄',r.record_date,s?.student_no,s?.name,r.record_type,r.content].map(q).join(',')+'\r\n';}download(`班主任資料-${today()}.csv`,'\ufeff'+csv,'text/csv;charset=utf-8');}
